### ISSUE TITLE
Hubot does not run Locally

### ISSUE THREAD

**Issue by zeknox** [codeandsupply/chat-bot-supplybot#12]
I recently performed a git clone of the this repo and then ran:

<pre>
$ bin/hubot
</pre>

I then get hit with this error.

<pre>
[Tue Dec 02 2014 11:08:52 GMT-0600 (CST)] ERROR Unable to load /Users/username/Documents/tools/hubot-pf/node_modules/hubot-scripts/src/scripts/mongolab-brain: TypeError: Cannot call method 'indexOf' of undefined
  at exports.parse (/Users/username/Documents/tools/hubot-pf/node_modules/mongodb/lib/mongodb/connection/url_parser.js:14:10)
  at Function.MongoClient.connect (/Users/username/Documents/tools/hubot-pf/node_modules/mongodb/lib/mongodb/mongo_client.js:164:16)
  at module.exports (/Users/username/Documents/tools/hubot-pf/node_modules/hubot-scripts/src/scripts/mongolab-brain.coffee:39:3, <js>:43:24)
  at Robot.loadFile (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/src/robot.coffee:217:9, <js>:163:24)
  at Robot.loadHubotScripts (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/src/robot.coffee:244:7, <js>:193:28)
  at Shell.loadScripts (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/bin/hubot:105:11, <js>:104:19)
  at Shell.EventEmitter.emit (events.js:92:17)
  at Shell.run (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/src/adapters/shell.coffee:40:5, <js>:84:12)
  at Robot.run (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/src/robot.coffee:437:5, <js>:391:27)
  at Object.<anonymous> (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/bin/hubot:135:8, <js>:146:11)
  at Object.<anonymous> (/Users/username/Documents/tools/hubot-pf/node_modules/hubot/bin/hubot:5:1, <js>:149:4)
  at Module._compile (module.js:456:26)
</pre>

Wondering if this is something on my end missing or something wrong with the repo?  Any insight would be appreciated.

**Comment by justinxreese** [comment]
I can't look into it today, but just want to confirm that I have the same issue

**Comment by cmluciano** [comment]
I believe this is do to the absence of mongo-brain on a local machine
